file:
  upload:
    path:
      txt: \home\ubuntu\salle\salle
mybatis:
  mapper-locations: com\example\salle\mapper\*.xml
  type-aliases-package: com\example\salle\domain\
server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: '!!ll067138'
    url: jdbc:mariadb://sallenew.cv59rxxz14yg.ap-northeast-2.rds.amazonaws.com:3306/
    username: salle
  mvc:
    static-path-pattern: /resources/**
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
cloud:
  aws:
    s3:
      bucket: sallestorage

debug: true